import { type NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import { signOut, useSession } from "next-auth/react";
import bg from "public/images/bg-022.png";
import logo from "public/images/logo.png";
import about_us from "public/images/about_us.png";
import contact_us from "public/images/contact.png";
import React, { useState, useEffect } from "react";

const Home: NextPage = () => {
  const [isLargeText, setIsLargeText] = useState(false);

  const [currentText, setCurrentText] = useState(0);
  const textList = [
    "You can search, get information, review, and\nrate apartments, bed spaces, hotels, dormitories,\nand transient spaces in Los Baños.",
    "Creating a home away from home, where comfort meets community.\nWelcome to STALS, where your journey towards success begins with a space\ndesigned to inspire, connect, and thrive",
    // "Text 3",
    // Add additional texts for the slideshow
  ];

  const splitText = (textList[currentText] ?? "").split("\n");

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentText((prevText) => (prevText + 1) % textList.length);
    }, 10000);

    return () => {
      clearInterval(interval);
    };
  }, [textList.length]);

  useEffect(() => {
    const handleResize = () => {
      setIsLargeText(window.innerWidth >= 768); // Adjust the breakpoint as needed
    };

    handleResize();

    window.addEventListener("resize", handleResize);

    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  return (
    <>
      <Head>
        <title>STALS</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* layout whole page */}
      <main className="">
        {/* landing page whole screen content */}
        <div className="">
          <img
            className="relative h-full w-screen bg-cover bg-fixed bg-center"
            src={bg.src}
            alt="background"
          />

          <div className="absolute inset-x-0 top-0 z-30">
            {/* 1 header nav bar [logo name home about contact]*/}
            <header
              className="absolute sticky top-0 z-50 justify-between text-white "
              id="up"
            >
              <div className="container mx-auto flex flex-col items-center justify-between py-4 lg:flex-row">
                <div className="mb-4 flex items-center lg:mb-0">
                  <Image src={logo} alt="Logo" className="mr-2 h-8 w-8" />
                  <span className="text-xl font-bold">STALS</span>
                </div>

                <nav className="flex items-center font-bold ">
                  <a
                    href="homepage"
                    className="mx-2 text-white no-underline hover:text-gray-300 hover:underline"
                  >
                    Home
                  </a>
                  <a
                    href="#contactus"
                    className="mx-2 text-white no-underline hover:text-gray-300 hover:underline"
                  >
                    Contact Us
                  </a>
                  <a
                    href="#aboutus"
                    className="mx-2 text-white no-underline hover:text-gray-300 hover:underline"
                  >
                    About Us
                  </a>
                </nav>
              </div>
            </header>
          </div>

          <section className="">
            <div className="absolute inset-0 z-20 flex flex-col items-center justify-center">
              <p
                className={`text-3xl font-extrabold tracking-tight lg:text-6xl xl:text-8xl ${
                  isLargeText ? "text-white" : "text-black"
                } ${isLargeText ? "pt-5" : "pt-20"} `}
              >
                Comfort At Its Best
              </p>

              <p
                className={`max-h-30 mt-2 overflow-hidden py-3 text-center font-sans text-sm lg:text-lg xl:text-xl ${
                  isLargeText ? "text-white" : "text-black"
                }`}
              >
                {splitText.map((line, index) => (
                  <React.Fragment key={index}>
                    {line}
                    <br />
                  </React.Fragment>
                ))}
              </p>

              {/* get started button edit color */}
              <div className="x flex flex-col items-center">
                <AuthShowcase />
              </div>
            </div>
          </section>

          <section className="mt-16 pt-40" id="aboutus">
            <div className="container mx-auto max-w-4xl">
              <div className="flex flex-col items-center justify-center gap-4 lg:flex-row lg:justify-between lg:gap-8">
                <div>
                  <img
                    className="floating-image h-60 w-auto lg:h-80"
                    src={about_us.src}
                    alt="aboutus"
                  />
                </div>
                <div className="text-center lg:text-left">
                  <h1 className="text-6xl font-bold">About Us</h1>
                  <p className="pt-3">
                    Cause there we are again when I loved you so
                    <br />
                    Back before you lost the one real thing
                    <br />
                    have ever known. It was rare, I was there
                  </p>
                </div>
              </div>
            </div>
          </section>

          <section className="mt-16 py-40" id="contactus">
            <div className="container mx-auto max-w-4xl">
              <div className="flex flex-col items-center justify-center gap-4 lg:flex-row lg:justify-between lg:gap-8">
                <div className="text-center lg:text-left">
                  <h1 className="text-6xl font-bold">Contact Us</h1>
                  <p className="pt-3">
                    Cause there we are again when I loved you so
                    <br />
                    Back before you lost the one real thing
                    <br />
                    have ever known. It was rare, I was there
                  </p>
                </div>

                <div>
                  <img
                    className="floating-image h-60 w-auto lg:h-80"
                    src={contact_us.src}
                    alt="contactus"
                  />
                </div>
              </div>
            </div>
          </section>
        </div>

        <footer className="bg-white dark:bg-gray-900">
          <div className="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
            <div className="md:flex md:justify-between">
              <div className="mb-6 md:mb-0">
                <a href="homepage" className="flex items-center">
                  <Image
                    src={logo}
                    className="mr-2 h-10 w-10"
                    alt="FlowBite Logo"
                  />
                  <span className="self-center whitespace-nowrap text-2xl font-semibold dark:text-white">
                    STALS
                  </span>
                </a>
              </div>
            </div>
            <hr className="my-6 border-gray-200 dark:border-gray-700 sm:mx-auto lg:my-8" />
            <div className="sm:flex sm:items-center sm:justify-between">
              <span className="text-sm text-gray-500 dark:text-gray-400 sm:text-center">
                © 2023{" "}
                <a href="homepage" className="hover:underline">
                  STALS
                </a>
                . All Rights Reserved.
              </span>
              <div className="mt-4 flex space-x-6 sm:mt-0 sm:justify-center">
                <a
                  href="#up"
                  className="mx-2 font-bold text-white no-underline hover:text-gray-300 hover:underline"
                >
                  Back to Top
                </a>
                <a
                  href="homepage"
                  className="mx-2 font-bold text-white no-underline hover:text-gray-300 hover:underline"
                >
                  Home
                </a>
              </div>
            </div>
          </div>
        </footer>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  const fullName = `${sessionData?.profile.first_name ?? ""} ${
    sessionData?.profile?.middle_name ?? ""
  } ${sessionData?.profile.last_name ?? ""}
  ${sessionData?.profile.Suffix ?? ""}`;
  return (
    <div className="flex flex-col items-start justify-start gap-4">
      <p className="text-start text-2xl text-white">
        {sessionData && <span>Logged in as {fullName}</span>}
      </p>
      <button
        className="rounded-full bg-[#1C5D99]/90 px-10 py-2 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={
          sessionData
            ? () => void signOut()
            : () => window.location.replace("/login")
        }
      >
        {sessionData ? "Sign out" : "Get Started"}
      </button>
    </div>
  );
};
