export default function TermsCondition() {
  return (
    <div className="">
      <h2 className="mb-4 text-center text-3xl font-bold text-p-dviolet">
        Terms and Conditions
      </h2>
      <div className="mb-4 h-60 max-w-xl overflow-y-scroll px-1">
        <p className="py-3 text-sm">
          Privacy Policy Last updated: May 28, 2023
          <br />
          <br />
          This document describes the policies and procedures used by the{" "}
          <span className="italic">Student</span>
          <br />
          <span className="italic">Accommodation and Lodging System</span>
          (STALS) on the collection, use and disclosure of
          <br />
          Your information when You use its Service. In addition, it includes
          information on Your
          <br />
          privacy rights and how the law protects You and Your information.
          <br />
          <br />
          The <span className="font-bold">Personal Data</span> You enter will be
          used to improve the Service provided to You by
          <br />
          STALS. By using this Service, You agree to the collection and use of
          information in
          <br />
          accordance with this Privacy Policy.
        </p>

        <h2 className="text-xl font-bold">
          <span>Interpretation and Definitions</span>
        </h2>
        <h3 className="pt-2 text-lg font-bold">
          <span>Interpretation</span>
        </h3>
        <p className="py-1 text-sm">
          The capitalized words are defined under the following conditions. The
          following definitions shall have the same meaning regardless of
          whether they appear in singular or in plural.
        </p>

        <h3 className="pt-2 text-lg font-bold">
          <span>Definition</span>
        </h3>
        <p className="py-1 text-sm">For the purposes of this Privacy Policy:</p>

        <div className="pl-4 text-sm">
          <p>
            <span className="font-bold">Account</span> refers to a unique
            account created for You to access our Service or parts of our
            Service.
          </p>
          <p>
            <span className="font-bold">Company</span> (referred to as either
            &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or
            &quot;Our&quot; in this Agreement) refers to STALS, Los Banos.
          </p>
          <p>
            <span className="font-bold">Cookies</span> are small files that are
            placed on Your computer, mobile device or any other device by a
            website, containing the details of Your browsing history on that
            website among its many uses.
          </p>
          <p>
            <span className="font-bold">Country</span> refers to the Philippines
          </p>
          <p>
            <span className="font-bold">Device</span> refers to any device that
            can access the Service such as a computer, a cell phone, or a
            digital tablet.
          </p>
          <p>
            <span className="font-bold">Personal Data</span> refers to any
            information that relates to an identified or identifiable
            individual.
          </p>
          <p>
            <span className="font-bold">Service</span> refers to the
            Website&apos;s usage as a way to find, rate, and review different
            accommodations and lodgings within two (2) kilometers off the edge
            of the UPLB campus.
          </p>
          <p>
            <span className="font-bold">Service Provider</span> means any
            natural or legal person who processes the data on behalf of the
            Company. It refers to third-party companies or individuals employed
            by the Company to facilitate the Service, to provide the Service on
            behalf of the Company, to perform services related to the Service or
            to assist the Company in analyzing how the Service is used.
          </p>
          <p>
            <span className="font-bold">Usage Data</span> refers to data
            collected automatically, either generated by the use of the Service
            or from the Service infrastructure itself (for example, the duration
            of a page visit).
          </p>
          <p>
            <span className="font-bold">Website</span> refers to STALS,
            accessible from https://stals.vercel.app/
          </p>
          <p>
            <span className="font-bold">You</span> refers to the individual
            accessing or using the Service, or the company, or other legal
            entity on behalf of which such individual is accessing or using the
            Service, as applicable.
          </p>
          <br />
        </div>

        <h2 className="text-xl font-bold">
          <span>Collecting and Using Your Personal Data</span>
        </h2>
        <h3 className="pt-2 text-lg font-bold">
          <span>Types of Data Collected</span>
        </h3>
        <p className="py-1 text-sm">For the purposes of this Privacy Policy:</p>

        <div className="pl-4 text-sm">
          <p>
            <span className="font-bold">Personal Data</span>
          </p>
          <p>
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
          </p>

          <ol className="list-inside list-disc pl-4">
            <li>Email address</li>
            <li>Full Name</li>
            <li>Contact Number</li>
            <li>Complete Address</li>
            <li>Images of property</li>
          </ol>
          <br />

          <p>
            <span className="font-bold">Usage Data</span>
          </p>
          <p>Usage Data is collected automatically when using the Service.</p>
          <br />
          <p>
            Usage Data may include information such as Your Device&apos;s
            Internet Protocol address (IP address), browser type, browser
            version, the pages of our Service that You visit, the time and date
            of Your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data.
          </p>
          <br />
          <p>
            When You access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device
            unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data.
          </p>
          <br />
          <p>
            We may also collect information that Your browser sends whenever You
            visit our Service.
          </p>
          <br />

          <p>
            <span className="font-bold">Tracking Technologies and Cookies</span>
          </p>
          <p>
            We use Cookies and similar tracking technologies to track the
            activity on Our Service and store certain information. Tracking
            technologies used are beacons, tags, and scripts to collect and
            track information and to improve and analyze Our Service. The
            technologies We use may include:
          </p>

          <ol className="list-inside list-disc pl-4">
            <li>
              <span className="font-bold">Cookies or Browser Cookies.</span> A
              cookie is a small file placed on Your Device. You can instruct
              Your browser to refuse all Cookies or to indicate when a Cookie is
              being sent. Parts of Our service may be unusable if You do not
              accept Cookies. Unless you have adjusted Your browser setting so
              that it will automatically refuse Cookies, our Service may use
              Cookies.
            </li>
            <li>
              <span className="font-bold">Web Beacons.</span> Certain sections
              of our Service and our emails may contain small electronic files
              known as web beacons (also referred to as clear gifs, pixel tags,
              and single-pixel gifs) that permit the Company, for example, to
              count users who have visited those pages or opened an email and
              for other related website statistics (for example, recording the
              popularity of a certain section and verifying system and server
              integrity).
            </li>
          </ol>
          <br />

          <p>
            Cookies can be &quot;Persistent&quot; or &quot;Session&quot;
            Cookies. Persistent Cookies remain on Your personal computer or
            mobile device when You go offline, while Session Cookies are deleted
            as soon as You close Your web browser. Learn more about cookies on
            the Free Privacy Policy website article.
          </p>
          <br />
          <p>
            We use both Session and Persistent Cookies for the purposes set out
            below:
          </p>

          <ol className="list-inside list-none pl-4">
            <li>
              <span className="font-bold">Necessary / Essential Cookies</span>
            </li>
            <ol className="list-inside list-none pl-5">
              <li>
                <span className="font-bold">Type:</span> Session Cookies
              </li>
              <li>
                <span className="font-bold">Purpose:</span> These Cookies are
                essential to provide You with services available through the
                Website and to enable You to use some of its features. They help
                to authenticate users and prevent fraudulent use of user
                accounts. Without these Cookies, the services that You have
                asked for cannot be provided, and We only use these Cookies to
                provide You with those services.
              </li>
            </ol>

            <li>
              <span className="font-bold">
                Cookies Policy / Notice Acceptance Cookies
              </span>
            </li>
            <ol className="list-inside list-none pl-5">
              <li>
                <span className="font-bold">Type:</span> Persistent Cookies
              </li>
              <li>
                <span className="font-bold">Purpose:</span> These Cookies
                identify if users have accepted the use of cookies on the
                Website.
              </li>
            </ol>

            <li>
              <span className="font-bold">Functionality Cookies</span>
            </li>
            <ol className="list-inside list-none pl-5">
              <li>
                <span className="font-bold">Type:</span> Persistent Cookies
              </li>
              <li>
                <span className="font-bold">Purpose:</span> These Cookies allow
                us to remember choices You make when You use the Website, such
                as remembering your login details or language preference. The
                purpose of these Cookies is to provide You with a more personal
                experience and to avoid You having to re-enter your preferences
                every time You use the Website.
              </li>
            </ol>
          </ol>
          <br />

          <p>
            For more information about the cookies we use and your choices
            regarding cookies, please visit our Cookies Policy or the Cookies
            section of our Privacy Policy.
          </p>
          <br />
        </div>

        <h3 className="pt-2 text-lg font-bold">
          <span>Use of Your Personal Data</span>
        </h3>
        <p className="py-1 text-sm">
          The Company may use Personal Data for the following purposes:
        </p>

        <div className="pl-4 text-sm">
          <p>
            <span className="font-bold">
              To provide and maintain our Service
            </span>
            , including to monitor the usage of our Service.
          </p>
          <p>
            <span className="font-bold">To manage Your Account:</span> to manage
            Your registration as a user of the Service. The Personal Data You
            provide can give You access to different functionalities of the
            Service that are available to You as a registered user.
          </p>
          <p>
            <span className="font-bold">
              For the performance of a contract:
            </span>
            the development, compliance and undertaking of the purchase contract
            for the products, items or services You have purchased or of any
            other contract with Us through the Service.
          </p>
          <p>
            <span className="font-bold">To contact You:</span> To contact You by
            email, telephone calls, SMS, or other equivalent forms of electronic
            communication, such as a mobile application&apos;s push
            notifications regarding updates or informative communications
            related to the functionalities, products or contracted services,
            including the security updates, when necessary or reasonable for
            their implementation.
          </p>
          <p>
            <span className="font-bold">To provide You</span> with news, special
            offers and general information about other goods, services and
            events which we offer that are similar to those that you have
            already purchased or enquired about unless You have opted not to
            receive such information.
          </p>
          <p>
            <span className="font-bold">To manage Your requests:</span> To
            attend and manage Your requests to Us.
          </p>
          <p>
            <span className="font-bold">For business transfers:</span> We may
            use Your information to evaluate or conduct a merger, divestiture,
            restructuring, reorganization, dissolution, or other sale or
            transfer of some or all of Our assets, whether as a going concern or
            as part of bankruptcy, liquidation, or similar proceeding, in which
            Personal Data held by Us about our Service users is among the assets
            transferred.
          </p>
          <p>
            <span className="font-bold">For other purposes:</span> We may use
            Your information for other purposes, such as data analysis,
            identifying usage trends, determining the effectiveness of our
            promotional campaigns and to evaluate and improve our Service,
            products, services, marketing and your experience.
          </p>
          <br />
        </div>

        <p className="py-1 text-sm">
          We may share Your personal information in the following situations:
        </p>

        <ol className="list-inside list-disc pl-4 text-sm">
          <li>
            <span className="font-bold">With Service Providers:</span> We may
            share Your personal information with Service Providers to monitor
            and analyze the use of our Service, to contact You.
          </li>
          <li>
            <span className="font-bold">With other users:</span> when You share
            personal information or otherwise interact in the public areas with
            other users, such information may be viewed by all users and may be
            publicly distributed outside
          </li>
          <li>
            <span className="font-bold">With Your consent:</span> We may
            disclose Your personal information for any other purpose with Your
            consent.
          </li>
        </ol>
        <br />

        <h3 className="pt-2 text-lg font-bold">
          <span>Types of Data Collected</span>
        </h3>
        <p className="text-sm">
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use Your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes, and
          enforce our legal agreements and policies.
        </p>
        <br />
        <p className="text-sm">
          The Company will also retain Usage Data for internal analysis
          purposes. Usage Data is generally retained for a shorter period of
          time, except when this data is used to strengthen the security or to
          improve the functionality of Our Service, or We are legally obligated
          to retain this data for longer time periods.
        </p>
        <br />

        <h3 className="pt-2 text-lg font-bold">
          <span>Delete Your Personal Data</span>
        </h3>
        <p className="text-sm">
          You have the right to delete or request that We assist in deleting the
          Personal Data that We have collected about You.
        </p>
        <br />
        <p className="text-sm">
          Our Service may give You the ability to delete certain information
          about You from within the Service.
        </p>
        <br />
        <p className="text-sm">
          You may update, amend, or delete Your information at any time by
          signing in to Your Account, if you have one, and visiting the account
          settings section that allows you to manage Your personal information.
          You may also contact Us to request access to, correct, or delete any
          personal information that You have provided to Us.
        </p>
        <br />
        <p className="text-sm">
          Please note, however, that We may need to retain certain information
          when we have a legal obligation or lawful basis to do so.
        </p>
        <br />

        <h3 className="pt-2 text-lg font-bold">
          <span>Disclosure of Your Personal Data</span>
        </h3>
        <ol className="list-inside list-none pl-4 text-sm">
          <li>
            <span className="font-bold">Law enforcement</span>
          </li>
          <ol className="list-inside list-none pl-5">
            <li>
              Under certain circumstances, the Company may be required to
              disclose Your Personal Data if required to do so by law or in
              response to valid requests by public authorities (e.g. a court or
              a government agency).
            </li>
          </ol>

          <li>
            <span className="font-bold">Other legal requirements</span>
          </li>
          <ol className="list-inside list-none pl-5">
            <li>
              The Company may disclose Your Personal Data in the good faith
              belief that such action is necessary to:
            </li>
            <ol className="list-inside list-disc pl-5">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>
                Prevent or investigate possible wrongdoing in connection with
                the Service
              </li>
              <li>
                Protect the personal safety of Users of the Service or the
                public
              </li>
              <li>Protect against legal liability</li>
            </ol>
          </ol>
        </ol>
        <br />

        <h3 className="pt-2 text-lg font-bold">
          <span>Security of Your Personal Data</span>
        </h3>
        <p className="text-sm">
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect Your Personal Data, We cannot guarantee
          its absolute security.
        </p>
        <br />

        <h3 className="pt-2 text-lg font-bold">
          <span>Children&apos;s Privacy</span>
        </h3>
        <p className="text-sm">
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If You are a parent or guardian and You are aware
          that Your child has provided Us with Personal Data, please contact Us.
          If We become aware that We have collected Personal Data from anyone
          under the age of 13 without verification of parental consent, We take
          steps to remove that information from Our servers.
          <br />
          <br />
          If We need to rely on consent as a legal basis for processing Your
          information and Your country requires consent from a parent, We may
          require Your parent&apos;s consent before We collect and use that
          information.
        </p>
        <br />

        <h3 className="pt-2 text-lg font-bold">
          <span>Links to Other Websites</span>
        </h3>
        <p className="text-sm">
          Our Service may contain links to other websites that are not operated
          by Us. If You click on a third party link, You will be directed to
          that third party&apos;s site. We strongly advise You to review the
          Privacy Policy of every site You visit.
          <br />
          <br />
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </p>
        <br />

        <h3 className="pt-2 text-lg font-bold">
          <span>Changes to this Privacy Policy</span>
        </h3>
        <p className="text-sm">
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page.
          <br />
          <br />
          We will let You know via email and/or a prominent notice on Our
          Service, prior to the change becoming effective and update the
          &quot;Last update&quot; date at the top of this Privacy Policy.
          <br />
          <br />
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>
        <br />

        <h3 className="pt-2 text-lg font-bold">
          <span>Contact Us</span>
        </h3>
        <p className="text-sm">
          If you have any questions about this Privacy Policy, You can contact
          us:
        </p>

        <ol className="list-inside list-disc pl-4 text-sm">
          <li>
            <span className="font-bold">By email:</span> uplb.stals@gmail.com
          </li>
        </ol>
        <br />
      </div>
    </div>
  );
}
